### PR TITLE
perf: use errors.New to replace fmt.Errorf with no parameters

### PR DESCRIPTION
**Pull request by ChengenH**
If you don't need to format the string, recommended to use error.New().

### CODE REVIEW

**Comment by 0xvbetsun** [comment]
hello @ChengenH, thank you for the enhancement! Would you mind changing `fmt.Errorf()` to `errors.New()` also in:
- [ ] `message.go`
- [ ] `transaction.go`
- [ ] `cmd/sinc/cmd/*.go`
- [x] `programs/address-lookup-tables/*.go`
- [ ] `programs/bpf-loader/loader.go`
- [ ] `programs/serum/*.go`
- [ ] `programs/system/*.go`
- [ ] `programs/token/*go`
- [ ] `programs/tokenregistry/*go`
- [ ] `rpc/types.go`
- [ ] `rpc/sendAndConfirmTransaction.go`
- [ ] `rpc/ws/blockSubscribe.go`
- [ ] `rpc/ws/signatureSubscribe.go`
- [ ] `vault/kmsgcp.go`
- [ ] `vault/passphrases.go`

to be consistent in your performance and style improvement.
If it is tedious for you, I'll do it

**Comment by ChengenH** [comment]
> hello @ChengenH, thank you for the enhancement! Would you mind changing `fmt.Errorf()` to `errors.New()` also in:
> 
> * [ ]  `message.go`
> * [ ]  `transaction.go`
> * [ ]  `cmd/sinc/cmd/*.go`
> * [x]  `programs/address-lookup-tables/*.go`
> * [ ]  `programs/bpf-loader/loader.go`
> * [ ]  `programs/serum/*.go`
> * [ ]  `programs/system/*.go`
> * [ ]  `programs/token/*go`
> * [ ]  `programs/tokenregistry/*go`
> * [ ]  `rpc/types.go`
> * [ ]  `rpc/sendAndConfirmTransaction.go`
> * [ ]  `rpc/ws/blockSubscribe.go`
> * [ ]  `rpc/ws/signatureSubscribe.go`
> * [ ]  `vault/kmsgcp.go`
> * [ ]  `vault/passphrases.go`
> 
> to be consistent in your performance and style improvement. If it is tedious for you, I'll do it

I'm done

**Review by 0xvbetsun — APPROVED** [review]
awesome!! thank you

**Comment by ChengenH** [comment]
> awesome!! thank you

I think you should check again

**Comment by gagliardetto** [comment]
this might create issues because `errors.New` returns an error that cannot be marshaled in json

**Pull request closed without merging**
