### PR TITLE
fix: base account should be optional in CreateAccountWithSeed

### PR DESCRIPTION
**Pull request by jiezhang**
I ran into a panic while calling `GetBaseAccount` on a `CreateAccountWithSeed` instruction : `panic: runtime error: index out of range [2] with length 2`. The instruction was decoded using `solana.DecodeInstruction` with real Solana data.

Here's an example of offending transaction: https://explorer.solana.com/tx/2xsXsEtxAouk58aFJoPYRa2DtEHDbEmRBZn8JqvdiowvK1wjqSR4DZ7S2DU78nPziUf2FBoWb2SWxYXVosRZoVe3

Its instruction data has only two accounts:
```
{ProgramIDIndex:7 Accounts:[0 1] Data:Zfn8kcNjVTJHkHFvtLJgJFyLF9k9RmsaHPGsAxywnvkqMpejbQcBDSjRdRfzeURhXpwdrEXe7J8ZNRGshfekC7fxQmKzbo6G1mQnBa8QmKGLrgHkjpxserMziPZSbYPcUqFaT5AGJmZvspZGY16yC6VV}
```

According to the doc [here](https://docs.rs/solana-program/1.10.8/solana_program/system_instruction/enum.SystemInstruction.html#variant.CreateAccountWithSeed), the base account field should be optional.

### CODE REVIEW

**Comment by jiezhang** [comment]
@gagliardetto Can you please take a look?

**Comment by gagliardetto** [comment]
hey @jiezhang thanks for the PR!

can you please also add a length check here: https://github.com/gagliardetto/solana-go/blob/44f2e49f2f7b68236988fb165a117d83cdde7298/programs/system/CreateAccountWithSeed.go#L202

**Comment by jiezhang** [comment]
@gagliardetto PTAL

**Comment by jiezhang** [comment]
Actually it makes more sense to fall back to the funding account when the base account is missing. This behavior is also consistent with the explorer: https://explorer.solana.com/tx/2xsXsEtxAouk58aFJoPYRa2DtEHDbEmRBZn8JqvdiowvK1wjqSR4DZ7S2DU78nPziUf2FBoWb2SWxYXVosRZoVe3

https://docs.rs/solana-program/1.10.8/solana_program/system_instruction/enum.SystemInstruction.html#variant.CreateAccountWithSeed
>[SIGNER] (optional) Base account; the account matching the base Pubkey below must be provided as a signer, but may be the same as the funding account and provided as account 0

**Comment by jiezhang** [comment]
@gagliardetto Gentle ping to review the PR.

**Comment by gagliardetto** [comment]
If I understand it correctly, if the third account is not defined, it defaults to the first account? Is that correct?

**Comment by gagliardetto** [comment]
Do you think this is correct? https://github.com/gagliardetto/solana-go/blob/2fc7ae7340c1091e80fe47aa318b6cbcc6f0bbb9/programs/system/CreateAccountWithSeed.go#L131-L133

**Comment by jiezhang** [comment]
> If I understand it correctly, if the third account is not defined, it defaults to the first account? Is that correct?

Yes, that behavior is consistent with the documentation and solana explorer.

**Comment by jiezhang** [comment]
> Do you think this is correct?
> 
> https://github.com/gagliardetto/solana-go/blob/2fc7ae7340c1091e80fe47aa318b6cbcc6f0bbb9/programs/system/CreateAccountWithSeed.go#L131-L133

I am not sure if this is correct. From what I have observed, the base field does equal to the first address (ie funding account) for many instructions, but according to the doc the base account should default to the funding account, not base field.

**Comment by jiezhang** [comment]
@gagliardetto Did you get the chance to look at it?

**Pull request closed without merging**
