### PR TITLE
Add GetConfirmedTransactionWithOpts

### PR DESCRIPTION
**Pull request by leoluk**

### CODE REVIEW

**Comment by leoluk** [comment]
I missed the comment you left on the commit. Thanks for building this fork!

**Comment by gagliardetto** [comment]
Thanks for your contribution!

**Comment by gagliardetto** [comment]
Is there anything else you have found yourself needing that solana-go doesn't have yet?

BTW, awesome job with the wormhole!

**Comment by leoluk** [comment]
It's still pretty hard to actually assemble custom instructions and derive accounts in anything not Rust. We actually ended up compiling Rust to WASM for our web UI because rewriting everything in JS would be too much effort.

**Pull request merged**
