### PR TITLE
chore: update dfuse logging to streamingfast logging

### PR DESCRIPTION
**Pull request by dcaf-mocha**
Notice the description of [dfuse-io](https://github.com/dfuse-io),
`dfuse is now StreamingFast - visit our new github.com/streamingfast`.

### CODE REVIEW

**Comment by dcaf-mocha** [comment]
@gagliardetto mind taking a look when you get a chance?

**Comment by gagliardetto** [comment]
Hey @dcaf-mocha 

Thanks for the PR!

- Did you encounter issues caused by the outdated version of the logging library?

**Comment by dcaf-mocha** [comment]
> Hey @dcaf-mocha
> 
> Thanks for the PR!
> 
> * Did you encounter issues caused by the outdated version of the logging library?

Yea I was getting issues updating my packages, unless I added the `replace` directive in my `go.mod`. 

( I can try and repro later if you are interested in the exact error message)

**Comment by dcaf-mocha** [comment]
> Hey @dcaf-mocha
> 
> Thanks for the PR!
> 
> * Did you encounter issues caused by the outdated version of the logging library?

Hey @gagliardetto do you need any additional info for this PR?

**Comment by gagliardetto** [comment]
Thank you @dcaf-mocha !

Sorry for the long wait.

**Pull request merged**
