### PR TITLE
Feature/maxtries transaction opts

### PR DESCRIPTION
**Pull request by sdrug**
Introducing `TransactionOps` struct and adding `maxTries` options to it.

### CODE REVIEW

**Comment by aalu1418** [comment]
Some additional context on why specifying the `maxRetries` parameter is useful in sending transactions:

https://docs.solana.com/developing/clients/jsonrpc-api#sendtransaction
> maxRetries: <usize> - (optional) Maximum number of times for the RPC node to retry sending the transaction to the leader. If this parameter not provided, the RPC node will retry the transaction until it is finalized or until the blockhash expires.

https://solanacookbook.com/guides/retrying-transactions.html#customizing-rebroadcast-logic
>In times of network congestion, it’s advantageous to set maxRetries to 0 and manually rebroadcast via a custom algorithm.

**Comment by aalu1418** [comment]
@gagliardetto any thoughts on this PR? ideally we would like to have this in soon 🙏🏼

**Comment by gagliardetto** [comment]
Hey @sdrug @aalu1418 

Thanks for the PR ^^

Other than a couple minor things, LGTM 

- Can you rename `GetRPCInput` to something like `ToMap` ?

**Comment by aalu1418** [comment]
> Can you rename GetRPCInput to something like ToMap ?

Changed! Please let me know if there's anything else, and thank you for the quick replies 😄

**Comment by gagliardetto** [comment]
Thanks!

**Pull request merged**
