### PR TITLE
Implement BPF Loader

### PR DESCRIPTION
**Pull request by lebdron**
Implement BPF loader according to JS and Rust sources

### CODE REVIEW

**Comment by lebdron** [comment]
> I agree. Composable pieces that can be used (and tested) individually without relying on hidden network calls.

Great, thanks! Then I'll refactor and push the updated code.

One remotely related question -- I also implemented the deployment and program call methods for Solang (https://github.com/hyperledger-labs/solang/blob/main/integration/solana/index.ts#L163) , but they depend on go-ethereum library. Do you think that adding go-ethereum as a dependency to solana-go is too much, and it's better to create another library which depends on go-ethereum and solana-go? Or it's OK to add the dependency here and add the code?

**Comment by lebdron** [comment]
@gagliardetto OK, the code seems to correspond close to Rust CLI implementation now.

**Comment by lebdron** [comment]
@gagliardetto I am not sure that I will be able to write tests in the near future because of other tasks. Right now it's "works on my machine" and the code can be checked against the reference implementation. I'd say it should be safe to add to the library as it does not affect other features, and tests can be implemented in the next pull requests.

**Comment by gagliardetto** [comment]
No problem! You already did an awesome great job here! I'll write the tests.

I'll try it out deploying some programs in the next few days.

Thanks for your work!

**Comment by lebdron** [comment]
@gagliardetto I'll just push one more update according to comments in this PR https://github.com/solana-labs/solana/pull/20895

**Comment by lebdron** [comment]
@gagliardetto I renamed the packaged and fixed the conditional branches

**Comment by gagliardetto** [comment]
Thank you @lebdron !!!

**Pull request merged**
